# Generated by Django 5.1.6 on 2025-02-18 19:21

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_remove_profile_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("number", models.CharField(max_length=50)),
                ("capacity", models.IntegerField()),
                (
                    "seats_available",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list, size=None
                    ),
                ),
                ("fare", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Bus",
                "verbose_name_plural": "Buses",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
            options={
                "verbose_name_plural": "Cities",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("ticket_id", models.AutoField(primary_key=True, serialize=False)),
                ("from_city", models.CharField(blank=True, max_length=50, null=True)),
                ("to_city", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "total_fare",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("ticket_seats", models.PositiveIntegerField(default=1)),
                ("ticket_time", models.DateTimeField()),
                (
                    "ticket_status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Booked"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="BOOKED",
                        max_length=20,
                    ),
                ),
                (
                    "ticket_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
                (
                    "ticket_bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus_booking.bus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("arrival_time", models.TimeField()),
                ("departure_time", models.TimeField()),
                ("stop_number", models.PositiveIntegerField()),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus_booking.bus",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus_booking.city",
                    ),
                ),
            ],
            options={
                "ordering": ["bus", "day"],
            },
        ),
        migrations.AddField(
            model_name="bus",
            name="cities",
            field=models.ManyToManyField(
                through="bus_booking.Schedule", to="bus_booking.city"
            ),
        ),
        migrations.CreateModel(
            name="BusFare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_city", models.CharField(max_length=50)),
                ("to_city", models.CharField(max_length=50)),
                ("fare", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "seat_type",
                    models.CharField(
                        choices=[
                            ("General", "General"),
                            ("Luxury", "Luxury"),
                            ("Sleeper", "Sleeper"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "conditioning",
                    models.CharField(
                        choices=[("AC", "AC"), ("Non-AC", "Non-AC")], max_length=50
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fares",
                        to="bus_booking.bus",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "bus",
                            "from_city",
                            "to_city",
                            "seat_type",
                            "conditioning",
                        ),
                        name="unique_bus_fare",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.UniqueConstraint(
                fields=("bus", "city", "day"), name="unique_bus_city_day"
            ),
        ),
    ]
