# Generated by Django 5.1.6 on 2025-02-07 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                ("bus_id", models.AutoField(primary_key=True, serialize=False)),
                ("bus_name", models.CharField(max_length=50)),
                ("bus_number", models.CharField(max_length=50)),
                ("bus_capacity", models.IntegerField()),
                ("bus_seats_available", models.IntegerField()),
                ("bus_fare", models.IntegerField()),
                ("bus_departure_time", models.DateTimeField()),
                ("bus_duration", models.IntegerField()),
                ("bus_starting_point", models.CharField(max_length=50)),
                ("bus_destination", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("ticket_id", models.AutoField(primary_key=True, serialize=False)),
                ("ticket_seats", models.IntegerField()),
                ("ticket_total_fare", models.IntegerField()),
                ("ticket_time", models.DateTimeField()),
                ("ticket_status", models.CharField(max_length=50)),
                (
                    "ticket_bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus_booking.bus",
                    ),
                ),
                (
                    "ticket_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
            ],
        ),
    ]
