# Generated by Django 5.1.6 on 2025-02-13 18:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_remove_profile_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                ("bus_id", models.AutoField(primary_key=True, serialize=False)),
                ("bus_name", models.CharField(max_length=50)),
                ("bus_number", models.CharField(max_length=50)),
                ("bus_capacity", models.IntegerField()),
                (
                    "bus_seats_available",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list, size=None
                    ),
                ),
                ("base_fare", models.IntegerField(blank=True, null=True)),
                (
                    "weekly_schedule",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("Monday", "Monday"),
                                ("Tuesday", "Tuesday"),
                                ("Wednesday", "Wednesday"),
                                ("Thursday", "Thursday"),
                                ("Friday", "Friday"),
                                ("Saturday", "Saturday"),
                                ("Sunday", "Sunday"),
                            ],
                            max_length=10,
                        ),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("bus_duration", models.IntegerField()),
                (
                    "bus_route",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bus",
                "verbose_name_plural": "Buses",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("ticket_id", models.AutoField(primary_key=True, serialize=False)),
                ("from_city", models.CharField(blank=True, max_length=50, null=True)),
                ("to_city", models.CharField(blank=True, max_length=50, null=True)),
                ("fare", models.IntegerField(blank=True, null=True)),
                ("ticket_seats", models.IntegerField()),
                ("ticket_time", models.DateTimeField()),
                ("ticket_status", models.CharField(max_length=50)),
                (
                    "ticket_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
                (
                    "ticket_bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus_booking.bus",
                    ),
                ),
            ],
        ),
    ]
