# Generated by Django 5.1.6 on 2025-02-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="cities",
            field=models.ManyToManyField(
                related_name="buses",
                through="bus_booking.Schedule",
                to="bus_booking.city",
            ),
        ),
    ]
