# Generated by Django 5.1.6 on 2025-02-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bus",
            options={"verbose_name": "Buses"},
        ),
        migrations.RemoveField(
            model_name="bus",
            name="bus_destination",
        ),
        migrations.RemoveField(
            model_name="bus",
            name="bus_starting_point",
        ),
        migrations.AddField(
            model_name="bus",
            name="bus_route",
            field=models.JSONField(default=list),
        ),
    ]
