# Generated by Django 5.1.6 on 2025-02-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bus_booking", "0002_alter_bus_cities"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="ticket_bus",
            new_name="bus",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="ticket_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="ticket_seats",
            new_name="seats",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="ticket_status",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="ticket_time",
            new_name="time",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="ticket_user",
            new_name="user",
        ),
    ]
