# Generated by Django 5.1.6 on 2025-02-11 10:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_booking", "0003_alter_bus_options_alter_bus_bus_route_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="bus_route",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50), default=list, size=None
            ),
        ),
    ]
