# Generated by Django 5.1.6 on 2025-03-21 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_booking", "0003_rename_ticket_bus_booking_bus_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="time",
            new_name="date_time",
        ),
        migrations.RemoveField(
            model_name="bus",
            name="seats_available",
        ),
        migrations.AlterField(
            model_name="booking",
            name="from_city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departures",
                to="bus_booking.city",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="to_city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrivals",
                to="bus_booking.city",
            ),
        ),
        migrations.DeleteModel(
            name="BusFare",
        ),
    ]
