# Generated by Django 5.1.6 on 2025-02-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bus_booking", "0004_alter_bus_bus_route"),
        ("users", "0002_remove_profile_user_phone"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ticket",
            new_name="Booking",
        ),
    ]
