# Generated by Django 5.1.6 on 2025-03-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_booking", "0004_rename_time_booking_date_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="seats",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
