# Generated by Django 5.1.6 on 2025-02-12 11:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_booking", "0005_rename_ticket_booking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus",
            name="bus_departure_time",
        ),
        migrations.AddField(
            model_name="bus",
            name="weekly_schedule",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Monday", "Monday"),
                        ("Tuesday", "Tuesday"),
                        ("Wednesday", "Wednesday"),
                        ("Thursday", "Thursday"),
                        ("Friday", "Friday"),
                        ("Saturday", "Saturday"),
                        ("Sunday", "Sunday"),
                    ],
                    max_length=10,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
