# Generated by Django 5.1.6 on 2025-03-25 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_booking", "0005_schedule_seats"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.PositiveIntegerField()),
                (
                    "seat_type",
                    models.CharField(
                        choices=[("Seater", "Seater"), ("Sleeper", "Sleeper")],
                        max_length=8,
                    ),
                ),
                (
                    "conditioning",
                    models.CharField(
                        choices=[("AC", "AC"), ("Non-AC", "Non-AC")], max_length=12
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="bus_booking.booking",
                    ),
                ),
            ],
        ),
    ]
