# Generated by Django 5.1.6 on 2025-03-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bus_booking", "0007_booking_booking_payment_ticket_ticket_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="date_time",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="status",
        ),
    ]
