# Generated by Django 5.1.6 on 2025-03-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bus_booking", "0008_remove_booking_date_time_remove_booking_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="otp_created_at",
            new_name="otp_date_time",
        ),
    ]
