# Generated by Django 5.1.6 on 2025-03-25 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bus_booking", "0009_rename_otp_created_at_booking_otp_date_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="otp_date_time",
        ),
    ]
