# Generated by Django 5.1.6 on 2025-03-25 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_booking", "0010_remove_booking_otp_date_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="seats",
        ),
        migrations.CreateModel(
            name="Journey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("seats", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bus_booking.schedule",
                    ),
                ),
            ],
        ),
    ]
