# Generated by Django 5.1.6 on 2025-03-25 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_booking", "0011_remove_schedule_seats_journey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="bus",
        ),
        migrations.AddField(
            model_name="booking",
            name="journey",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="bus_booking.journey",
            ),
        ),
    ]
