# Generated by Django 5.1.6 on 2025-03-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_booking", "0014_booking_booking_date_booking_journey_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="journey_date",
            field=models.DateTimeField(null=True),
        ),
    ]
