services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    environment:
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: AbhiAshi@123
      POSTGRES_DB: busdj
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data: